name: Build and Deploy via FTP

on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur la branche principale
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Utilise l'image Ubuntu pour exécuter les actions

    steps:
      # 1. Vérifier le code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Installer Node.js (backend et frontend)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Spécifie la version de Node.js

      # 3. Installer les dépendances backend
      - name: Install backend dependencies
        working-directory: ./backend  # Spécifie le répertoire backend
        run: |
          npm install

      # 4. Installer les dépendances frontend
      - name: Install frontend dependencies
        working-directory: ./frontend  # Spécifie le répertoire frontend
        run: |
          npm install

      # 5. Construire l'application frontend (Vue.js)
      - name: Build frontend
        working-directory: ./frontend  # Spécifie le répertoire frontend
        run: |
          npm run build  # Cette commande génère le dossier 'dist'

      # 6. Copier le dossier 'dist' dans le backend pour qu'il soit servi par Express
      - name: Copy dist to backend
        run: |
          cp -r ./frontend/dist ./backend/  # Copie le dossier dist du frontend dans le backend

      # 7. Déployer via FTP sur le serveur distant
      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}        # L'adresse du serveur FTP
          username: ${{ secrets.FTP_USER }}    #  Nom d'utilisateur FTP
          password: ${{ secrets.FTP_PASS }}    # Mot de passe FTP
          protocol: ftps
          port: 21
          local-dir: ./backend/dist/               # Dossier local à déployer (ici le dossier dist du backend)
          remote-dir: /path/to/your/remote/folder  # Dossier dista